# Generated by Django 3.1.5 on 2021-01-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='date_posted',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_deadline',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_description',
            field=models.CharField(default='None', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_location',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_salary',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='technologies',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='work_schedule',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_title',
            field=models.CharField(max_length=200),
        ),
    ]
